name: Lint

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
